/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PiiConfig } from "./PiiConfig";
import type { PostCallAnalysisDataBooleanAnalysisData } from "./PostCallAnalysisDataBooleanAnalysisData";
import type { PostCallAnalysisDataEnumAnalysisData } from "./PostCallAnalysisDataEnumAnalysisData";
import type { PostCallAnalysisDataNumberAnalysisData } from "./PostCallAnalysisDataNumberAnalysisData";
import type { PostCallAnalysisDataStringAnalysisData } from "./PostCallAnalysisDataStringAnalysisData";
import type { PronunciationDictionary } from "./PronunciationDictionary";
import type { ResponseEngineResponseEngineConversationFlow } from "./ResponseEngineResponseEngineConversationFlow";
import type { ResponseEngineResponseEngineCustomLm } from "./ResponseEngineResponseEngineCustomLm";
import type { ResponseEngineResponseEngineRetellLm } from "./ResponseEngineResponseEngineRetellLm";
import type { UserDtmfOptions } from "./UserDtmfOptions";
import type { VoicemailOption } from "./VoicemailOption";

export const agentResponseAmbientSoundEnum = {
    "coffee-shop": "coffee-shop",
    "convention-hall": "convention-hall",
    "summer-outdoor": "summer-outdoor",
    "mountain-outdoor": "mountain-outdoor",
    "static-noise": "static-noise",
    "call-center": "call-center"
} as const;

export type AgentResponseAmbientSoundEnumKey = (typeof agentResponseAmbientSoundEnum)[keyof typeof agentResponseAmbientSoundEnum];

export const agentResponseDataStorageSettingEnum = {
    "everything": "everything",
    "everything_except_pii": "everything_except_pii",
    "basic_attributes_only": "basic_attributes_only"
} as const;

export type AgentResponseDataStorageSettingEnumKey = (typeof agentResponseDataStorageSettingEnum)[keyof typeof agentResponseDataStorageSettingEnum];

export const agentResponseDenoisingModeEnum = {
    "noise-cancellation": "noise-cancellation",
    "noise-and-background-speech-cancellation": "noise-and-background-speech-cancellation"
} as const;

export type AgentResponseDenoisingModeEnumKey = (typeof agentResponseDenoisingModeEnum)[keyof typeof agentResponseDenoisingModeEnum];

export const agentResponseLanguageEnum = {
    "en-US": "en-US",
    "en-IN": "en-IN",
    "en-GB": "en-GB",
    "en-AU": "en-AU",
    "en-NZ": "en-NZ",
    "de-DE": "de-DE",
    "es-ES": "es-ES",
    "es-419": "es-419",
    "hi-IN": "hi-IN",
    "fr-FR": "fr-FR",
    "fr-CA": "fr-CA",
    "ja-JP": "ja-JP",
    "pt-PT": "pt-PT",
    "pt-BR": "pt-BR",
    "zh-CN": "zh-CN",
    "ru-RU": "ru-RU",
    "it-IT": "it-IT",
    "ko-KR": "ko-KR",
    "nl-NL": "nl-NL",
    "nl-BE": "nl-BE",
    "pl-PL": "pl-PL",
    "tr-TR": "tr-TR",
    "vi-VN": "vi-VN",
    "ro-RO": "ro-RO",
    "bg-BG": "bg-BG",
    "ca-ES": "ca-ES",
    "th-TH": "th-TH",
    "da-DK": "da-DK",
    "fi-FI": "fi-FI",
    "el-GR": "el-GR",
    "hu-HU": "hu-HU",
    "id-ID": "id-ID",
    "no-NO": "no-NO",
    "sk-SK": "sk-SK",
    "sv-SE": "sv-SE",
    "ms-MY": "ms-MY",
    "af-ZA": "af-ZA",
    "ar-SA": "ar-SA",
    "az-AZ": "az-AZ",
    "bs-BA": "bs-BA",
    "cy-GB": "cy-GB",
    "fa-IR": "fa-IR",
    "fil-PH": "fil-PH",
    "gl-ES": "gl-ES",
    "he-IL": "he-IL",
    "hr-HR": "hr-HR",
    "hy-AM": "hy-AM",
    "is-IS": "is-IS",
    "kk-KZ": "kk-KZ",
    "kn-IN": "kn-IN",
    "mk-MK": "mk-MK",
    "mr-IN": "mr-IN",
    "ne-NP": "ne-NP",
    "sl-SI": "sl-SI",
    "sr-RS": "sr-RS",
    "sw-KE": "sw-KE",
    "ta-IN": "ta-IN",
    "ur-IN": "ur-IN",
    "yue-CN": "yue-CN",
    "uk-UA": "uk-UA",
    "multi": "multi"
} as const;

export type AgentResponseLanguageEnumKey = (typeof agentResponseLanguageEnum)[keyof typeof agentResponseLanguageEnum];

export const agentResponsePostCallAnalysisModelEnum = {
    "gpt-4.1": "gpt-4.1",
    "gpt-4.1-mini": "gpt-4.1-mini",
    "gpt-4.1-nano": "gpt-4.1-nano",
    "gpt-5": "gpt-5",
    "gpt-5.1": "gpt-5.1",
    "gpt-5.2": "gpt-5.2",
    "gpt-5-mini": "gpt-5-mini",
    "gpt-5-nano": "gpt-5-nano",
    "claude-4.5-sonnet": "claude-4.5-sonnet",
    "claude-4.5-haiku": "claude-4.5-haiku",
    "gemini-2.5-flash": "gemini-2.5-flash",
    "gemini-2.5-flash-lite": "gemini-2.5-flash-lite"
} as const;

export type AgentResponsePostCallAnalysisModelEnumKey = (typeof agentResponsePostCallAnalysisModelEnum)[keyof typeof agentResponsePostCallAnalysisModelEnum];

export const agentResponseSttModeEnum = {
    "fast": "fast",
    "accurate": "accurate"
} as const;

export type AgentResponseSttModeEnumKey = (typeof agentResponseSttModeEnum)[keyof typeof agentResponseSttModeEnum];

export const agentResponseVocabSpecializationEnum = {
    "general": "general",
    "medical": "medical"
} as const;

export type AgentResponseVocabSpecializationEnumKey = (typeof agentResponseVocabSpecializationEnum)[keyof typeof agentResponseVocabSpecializationEnum];

export const agentResponseVoiceModelEnum = {
    "eleven_turbo_v2": "eleven_turbo_v2",
    "eleven_flash_v2": "eleven_flash_v2",
    "eleven_turbo_v2_5": "eleven_turbo_v2_5",
    "eleven_flash_v2_5": "eleven_flash_v2_5",
    "eleven_multilingual_v2": "eleven_multilingual_v2",
    "sonic-2": "sonic-2",
    "sonic-3": "sonic-3",
    "sonic-turbo": "sonic-turbo",
    "tts-1": "tts-1",
    "gpt-4o-mini-tts": "gpt-4o-mini-tts",
    "speech-02-turbo": "speech-02-turbo"
} as const;

export type AgentResponseVoiceModelEnumKey = (typeof agentResponseVoiceModelEnum)[keyof typeof agentResponseVoiceModelEnum];

export type AgentResponse = {
    /**
     * @type string
    */
    agent_id: string;
    /**
     * @type integer
    */
    last_modification_timestamp: number;
    response_engine: (ResponseEngineResponseEngineRetellLm | ResponseEngineResponseEngineCustomLm | ResponseEngineResponseEngineConversationFlow);
    /**
     * @type integer
    */
    version: number;
    /**
     * @type string
    */
    voice_id: string;
    agent_name?: (string | null);
    allow_user_dtmf?: (boolean | null);
    ambient_sound?: (AgentResponseAmbientSoundEnumKey | null);
    ambient_sound_volume?: (number | null);
    analysis_successful_prompt?: (string | null);
    analysis_summary_prompt?: (string | null);
    backchannel_frequency?: (number | null);
    backchannel_words?: (string[] | null);
    begin_message_delay_ms?: (number | null);
    boosted_keywords?: (string[] | null);
    data_storage_setting?: (AgentResponseDataStorageSettingEnumKey | null);
    denoising_mode?: (AgentResponseDenoisingModeEnumKey | null);
    enable_backchannel?: (boolean | null);
    enable_voicemail_detection?: (boolean | null);
    end_call_after_silence_ms?: (number | null);
    fallback_voice_ids?: (string[] | null);
    interruption_sensitivity?: (number | null);
    is_published?: (boolean | null);
    language?: (AgentResponseLanguageEnumKey | null);
    max_call_duration_ms?: (number | null);
    normalize_for_speech?: (boolean | null);
    opt_in_signed_url?: (boolean | null);
    pii_config?: (PiiConfig | null);
    post_call_analysis_data?: ((PostCallAnalysisDataStringAnalysisData | PostCallAnalysisDataEnumAnalysisData | PostCallAnalysisDataBooleanAnalysisData | PostCallAnalysisDataNumberAnalysisData)[] | null);
    post_call_analysis_model?: (AgentResponsePostCallAnalysisModelEnumKey | null);
    pronunciation_dictionary?: (PronunciationDictionary[] | null);
    reminder_max_count?: (number | null);
    reminder_trigger_ms?: (number | null);
    responsiveness?: (number | null);
    ring_duration_ms?: (number | null);
    signed_url_expiration_ms?: (number | null);
    stt_mode?: (AgentResponseSttModeEnumKey | null);
    user_dtmf_options?: (UserDtmfOptions | null);
    version_description?: (string | null);
    vocab_specialization?: (AgentResponseVocabSpecializationEnumKey | null);
    voice_model?: (AgentResponseVoiceModelEnumKey | null);
    voice_speed?: (number | null);
    voice_temperature?: (number | null);
    voicemail_detection_timeout_ms?: (number | null);
    voicemail_message?: (string | null);
    voicemail_option?: (VoicemailOption | null);
    volume?: (number | null);
    webhook_timeout_ms?: (number | null);
    webhook_url?: (string | null);
    [key: string]: any;
};