/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Minimal request schema for updating an existing agent via our API.
*/
export type AgentUpdateRequest = {
    /**
     * @description Updated system prompt (creates a new LLM and updates the agent)
    */
    prompt?: (string | null);
    /**
     * @description Updated name for the agent (for internal reference)
    */
    agent_name?: (string | null);
};