/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Response schema for retrieving a single agent.
*/
export type AgentGetResponse = {
    /**
     * @description Unique identifier for the agent
     * @type string
    */
    agent_id: string;
    /**
     * @description Name of the agent (for internal reference)
    */
    name?: (string | null);
    /**
     * @description The system prompt defining agent behavior
    */
    prompt?: (string | null);
};