/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Schema for call response.
*/
export type CallResponse = {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type string
    */
    retell_agent_id: string;
    /**
     * @type string
    */
    driver_name: string;
    /**
     * @type string
    */
    phone_number: string;
    /**
     * @type string
    */
    load_number: string;
    /**
     * @type string
    */
    status: string;
    retell_call_id: (string | null);
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type string, date-time
    */
    updated_at: string;
};