/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Schema for triggering a call.
*/
export type CallCreate = {
    /**
     * @type string
    */
    agent_id: string;
    /**
     * @type string
    */
    driver_name: string;
    /**
     * @type string
    */
    phone_number: string;
    /**
     * @type string
    */
    load_number: string;
};