/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Schema for call response.
*/
export type CallResponse = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    agent_id: string;
    /**
     * @type string
    */
    driver_name: string;
    /**
     * @type string
    */
    phone_number: string;
    /**
     * @type string
    */
    load_number: string;
    /**
     * @type string
    */
    status: string;
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type string, date-time
    */
    updated_at: string;
    transcript?: (string | null);
    structured_data?: ({
        [key: string]: any;
    } | null);
};