/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AgentCreateRequest } from "./AgentCreateRequest";
import type { AgentResponse } from "./AgentResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

/**
 * @description Successful Response
*/
export type CreateAgentConfigApiAgentConfigsPost201 = AgentResponse;

/**
 * @description Validation Error
*/
export type CreateAgentConfigApiAgentConfigsPost422 = HTTPValidationError;

export type CreateAgentConfigApiAgentConfigsPostMutationRequest = AgentCreateRequest;

export type CreateAgentConfigApiAgentConfigsPostMutationResponse = CreateAgentConfigApiAgentConfigsPost201;

export type CreateAgentConfigApiAgentConfigsPostMutation = {
    Response: CreateAgentConfigApiAgentConfigsPost201;
    Request: CreateAgentConfigApiAgentConfigsPostMutationRequest;
    Errors: CreateAgentConfigApiAgentConfigsPost422;
};