/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CallCreate } from "./CallCreate";
import type { HTTPValidationError } from "./HTTPValidationError";

/**
 * @description Successful Response
*/
export type CreateWebCallApiCallswebcallPost201 = any;

/**
 * @description Validation Error
*/
export type CreateWebCallApiCallswebcallPost422 = HTTPValidationError;

export type CreateWebCallApiCallswebcallPostMutationRequest = CallCreate;

export type CreateWebCallApiCallswebcallPostMutationResponse = CreateWebCallApiCallswebcallPost201;

export type CreateWebCallApiCallswebcallPostMutation = {
    Response: CreateWebCallApiCallswebcallPost201;
    Request: CreateWebCallApiCallswebcallPostMutationRequest;
    Errors: CreateWebCallApiCallswebcallPost422;
};