/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError";
import type { WebCallCreateRequest } from "./WebCallCreateRequest";

/**
 * @description Successful Response
*/
export type CreateWebCallApiWebCallsPost201 = any;

/**
 * @description Validation Error
*/
export type CreateWebCallApiWebCallsPost422 = HTTPValidationError;

export type CreateWebCallApiWebCallsPostMutationRequest = WebCallCreateRequest;

export type CreateWebCallApiWebCallsPostMutationResponse = CreateWebCallApiWebCallsPost201;

export type CreateWebCallApiWebCallsPostMutation = {
    Response: CreateWebCallApiWebCallsPost201;
    Request: CreateWebCallApiWebCallsPostMutationRequest;
    Errors: CreateWebCallApiWebCallsPost422;
};