/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AgentGetResponse } from "./AgentGetResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

export type GetAgentConfigApiAgentConfigsAgentIdGetPathParams = {
    /**
     * @type string
    */
    agent_id: string;
};

/**
 * @description Successful Response
*/
export type GetAgentConfigApiAgentConfigsAgentIdGet200 = AgentGetResponse;

/**
 * @description Validation Error
*/
export type GetAgentConfigApiAgentConfigsAgentIdGet422 = HTTPValidationError;

export type GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse = GetAgentConfigApiAgentConfigsAgentIdGet200;

export type GetAgentConfigApiAgentConfigsAgentIdGetQuery = {
    Response: GetAgentConfigApiAgentConfigsAgentIdGet200;
    PathParams: GetAgentConfigApiAgentConfigsAgentIdGetPathParams;
    Errors: GetAgentConfigApiAgentConfigsAgentIdGet422;
};