/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CallResponse } from "./CallResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

export type GetCallApiCallsCallIdGetPathParams = {
    /**
     * @type string
    */
    call_id: string;
};

/**
 * @description Successful Response
*/
export type GetCallApiCallsCallIdGet200 = CallResponse;

/**
 * @description Validation Error
*/
export type GetCallApiCallsCallIdGet422 = HTTPValidationError;

export type GetCallApiCallsCallIdGetQueryResponse = GetCallApiCallsCallIdGet200;

export type GetCallApiCallsCallIdGetQuery = {
    Response: GetCallApiCallsCallIdGet200;
    PathParams: GetCallApiCallsCallIdGetPathParams;
    Errors: GetCallApiCallsCallIdGet422;
};