/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type GetInitialPromptApiAgentConfigsInitialPromptGet200 = {
    [key: string]: string;
};

export type GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse = GetInitialPromptApiAgentConfigsInitialPromptGet200;

export type GetInitialPromptApiAgentConfigsInitialPromptGetQuery = {
    Response: GetInitialPromptApiAgentConfigsInitialPromptGet200;
    Errors: any;
};