/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CallResponse } from "./CallResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

export type ListCallsApiCallsGetQueryParams = {
    /**
     * @default 0
     * @type integer | undefined
    */
    skip?: number;
    /**
     * @default 100
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description Successful Response
*/
export type ListCallsApiCallsGet200 = CallResponse[];

/**
 * @description Validation Error
*/
export type ListCallsApiCallsGet422 = HTTPValidationError;

export type ListCallsApiCallsGetQueryResponse = ListCallsApiCallsGet200;

export type ListCallsApiCallsGetQuery = {
    Response: ListCallsApiCallsGet200;
    QueryParams: ListCallsApiCallsGetQueryParams;
    Errors: ListCallsApiCallsGet422;
};