/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AgentResponse } from "./AgentResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

export type ListAgentConfigsApiAgentConfigsGetQueryParams = {
    /**
     * @minLength 1
     * @maxLength 1000
     * @default 1000
     * @type integer | undefined
    */
    limit?: number;
    pagination_key?: (string | null);
};

/**
 * @description Successful Response
*/
export type ListAgentConfigsApiAgentConfigsGet200 = AgentResponse[];

/**
 * @description Validation Error
*/
export type ListAgentConfigsApiAgentConfigsGet422 = HTTPValidationError;

export type ListAgentConfigsApiAgentConfigsGetQueryResponse = ListAgentConfigsApiAgentConfigsGet200;

export type ListAgentConfigsApiAgentConfigsGetQuery = {
    Response: ListAgentConfigsApiAgentConfigsGet200;
    QueryParams: ListAgentConfigsApiAgentConfigsGetQueryParams;
    Errors: ListAgentConfigsApiAgentConfigsGet422;
};