/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const piiConfigCategoriesEnum = {
    "person_name": "person_name",
    "address": "address",
    "email": "email",
    "phone_number": "phone_number",
    "ssn": "ssn",
    "passport": "passport",
    "driver_license": "driver_license",
    "credit_card": "credit_card",
    "bank_account": "bank_account",
    "password": "password",
    "pin": "pin",
    "medical_id": "medical_id",
    "date_of_birth": "date_of_birth",
    "customer_account_number": "customer_account_number"
} as const;

export type PiiConfigCategoriesEnumKey = (typeof piiConfigCategoriesEnum)[keyof typeof piiConfigCategoriesEnum];

/**
 * @description Configuration for PII scrubbing from transcripts and recordings.
*/
export type PiiConfig = {
    /**
     * @type array
    */
    categories: PiiConfigCategoriesEnumKey[];
    /**
     * @type string
    */
    mode: "post_call";
    [key: string]: any;
};