/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostCallAnalysisDataBooleanAnalysisData = {
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    type: "boolean";
    [key: string]: any;
};