/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostCallAnalysisDataStringAnalysisData = {
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    type: "string";
    examples?: (string[] | null);
    [key: string]: any;
};