/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PostCallAnalysisDataEnumAnalysisData = {
    /**
     * @type array
    */
    choices: string[];
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    type: "enum";
    [key: string]: any;
};