/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const pronunciationDictionaryAlphabetEnum = {
    "ipa": "ipa",
    "cmu": "cmu"
} as const;

export type PronunciationDictionaryAlphabetEnumKey = (typeof pronunciationDictionaryAlphabetEnum)[keyof typeof pronunciationDictionaryAlphabetEnum];

export type PronunciationDictionary = {
    /**
     * @type string
    */
    alphabet: PronunciationDictionaryAlphabetEnumKey;
    /**
     * @type string
    */
    phoneme: string;
    /**
     * @type string
    */
    word: string;
    [key: string]: any;
};