/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResponseEngineResponseEngineRetellLm = {
    /**
     * @type string
    */
    llm_id: string;
    /**
     * @type string
    */
    type: "retell-llm";
    version?: (number | null);
    [key: string]: any;
};