/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResponseEngineResponseEngineCustomLm = {
    /**
     * @type string
    */
    llm_websocket_url: string;
    /**
     * @type string
    */
    type: "custom-llm";
    [key: string]: any;
};