/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ResponseEngineResponseEngineConversationFlow = {
    /**
     * @type string
    */
    conversation_flow_id: string;
    /**
     * @type string
    */
    type: "conversation-flow";
    version?: (number | null);
    [key: string]: any;
};