/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type RetellWebhookApiWebhooksRetellPost204 = any;

export type RetellWebhookApiWebhooksRetellPostMutationResponse = RetellWebhookApiWebhooksRetellPost204;

export type RetellWebhookApiWebhooksRetellPostMutation = {
    Response: RetellWebhookApiWebhooksRetellPost204;
    Errors: any;
};