/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CallCreate } from "./CallCreate";
import type { CallResponse } from "./CallResponse";
import type { HTTPValidationError } from "./HTTPValidationError";

/**
 * @description Successful Response
*/
export type TriggerCallApiCallsTriggerPost201 = CallResponse;

/**
 * @description Validation Error
*/
export type TriggerCallApiCallsTriggerPost422 = HTTPValidationError;

export type TriggerCallApiCallsTriggerPostMutationRequest = CallCreate;

export type TriggerCallApiCallsTriggerPostMutationResponse = TriggerCallApiCallsTriggerPost201;

export type TriggerCallApiCallsTriggerPostMutation = {
    Response: TriggerCallApiCallsTriggerPost201;
    Request: TriggerCallApiCallsTriggerPostMutationRequest;
    Errors: TriggerCallApiCallsTriggerPost422;
};