/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AgentResponse } from "./AgentResponse";
import type { AgentUpdateRequest } from "./AgentUpdateRequest";
import type { HTTPValidationError } from "./HTTPValidationError";

export type UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams = {
    /**
     * @type string
    */
    agent_id: string;
};

/**
 * @description Successful Response
*/
export type UpdateAgentConfigApiAgentConfigsAgentIdPatch200 = AgentResponse;

/**
 * @description Validation Error
*/
export type UpdateAgentConfigApiAgentConfigsAgentIdPatch422 = HTTPValidationError;

export type UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest = AgentUpdateRequest;

export type UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse = UpdateAgentConfigApiAgentConfigsAgentIdPatch200;

export type UpdateAgentConfigApiAgentConfigsAgentIdPatchMutation = {
    Response: UpdateAgentConfigApiAgentConfigsAgentIdPatch200;
    Request: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest;
    PathParams: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams;
    Errors: UpdateAgentConfigApiAgentConfigsAgentIdPatch422;
};