/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserDtmfOptions = {
    digit_limit?: (number | null);
    termination_key?: (string | null);
    timeout_ms?: (number | null);
    [key: string]: any;
};