/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type VoicemailOptionActionVoicemailActionStaticText = {
    /**
     * @type string
    */
    text: string;
    /**
     * @type string
    */
    type: "static_text";
    [key: string]: any;
};