/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VoicemailOptionActionVoicemailActionBridgeTransfer } from "./VoicemailOptionActionVoicemailActionBridgeTransfer";
import type { VoicemailOptionActionVoicemailActionHangup } from "./VoicemailOptionActionVoicemailActionHangup";
import type { VoicemailOptionActionVoicemailActionPrompt } from "./VoicemailOptionActionVoicemailActionPrompt";
import type { VoicemailOptionActionVoicemailActionStaticText } from "./VoicemailOptionActionVoicemailActionStaticText";

/**
 * @description If this option is set, the call will try to detect voicemail in the first 3 minutes of the call. Actions defined (hangup, or leave a message) will be applied when the voicemail is detected. Set this to null to disable voicemail detection.
*/
export type VoicemailOption = {
    action: (VoicemailOptionActionVoicemailActionPrompt | VoicemailOptionActionVoicemailActionStaticText | VoicemailOptionActionVoicemailActionHangup | VoicemailOptionActionVoicemailActionBridgeTransfer);
    [key: string]: any;
};