/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type VoicemailOptionActionVoicemailActionBridgeTransfer = {
    /**
     * @type string
    */
    type: "bridge_transfer";
    [key: string]: any;
};