/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type VoicemailOptionActionVoicemailActionHangup = {
    /**
     * @type string
    */
    type: "hangup";
    [key: string]: any;
};