/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type VoicemailOptionActionVoicemailActionPrompt = {
    /**
     * @type string
    */
    text: string;
    /**
     * @type string
    */
    type: "prompt";
    [key: string]: any;
};