/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Schema for creating a web call.
*/
export type WebCallCreateRequest = {
    /**
     * @description Unique ID of agent used for the call
     * @type string
    */
    agent_id: string;
    /**
     * @description Arbitrary key-value storage for internal use (e.g., customer IDs)
    */
    metadata?: ({
        [key: string]: any;
    } | null);
    /**
     * @description Dynamic string variables to inject into prompt and tool descriptions
    */
    retell_llm_dynamic_variables?: ({
        [key: string]: string;
    } | null);
};