/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateAgentConfigApiAgentConfigsPostMutationRequest, CreateAgentConfigApiAgentConfigsPostMutationResponse, CreateAgentConfigApiAgentConfigsPost422 } from "../../types/CreateAgentConfigApiAgentConfigsPost";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createAgentConfigApiAgentConfigsPostMutationKey = () => [{ url: '/api/agent-configs' }] as const

export type CreateAgentConfigApiAgentConfigsPostMutationKey = ReturnType<typeof createAgentConfigApiAgentConfigsPostMutationKey>

/**
 * @description Create a new agent configuration in Retell AI.This is a light wrapper that creates an agent with sensible defaults.You only need to provide the prompt text - all other configuration(voice, model, responsiveness, etc.) is handled by our API.Args:    request: Agent creation request with prompt and optional nameReturns:    AgentResponse: The created agent from Retell SDK
 * @summary Create Agent Config
 * {@link /api/agent-configs}
 */
export async function createAgentConfigApiAgentConfigsPost(data: CreateAgentConfigApiAgentConfigsPostMutationRequest, config: Partial<RequestConfig<CreateAgentConfigApiAgentConfigsPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, CreateAgentConfigApiAgentConfigsPostMutationRequest>({ method : "POST", url : `/api/agent-configs`, data : requestData, ... requestConfig })  
  return res.data
}

export function createAgentConfigApiAgentConfigsPostMutationOptions(config: Partial<RequestConfig<CreateAgentConfigApiAgentConfigsPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createAgentConfigApiAgentConfigsPostMutationKey()
  return mutationOptions<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, {data: CreateAgentConfigApiAgentConfigsPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createAgentConfigApiAgentConfigsPost(data, config)
    },
  })
}

/**
 * @description Create a new agent configuration in Retell AI.This is a light wrapper that creates an agent with sensible defaults.You only need to provide the prompt text - all other configuration(voice, model, responsiveness, etc.) is handled by our API.Args:    request: Agent creation request with prompt and optional nameReturns:    AgentResponse: The created agent from Retell SDK
 * @summary Create Agent Config
 * {@link /api/agent-configs}
 */
export function useCreateAgentConfigApiAgentConfigsPost<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, {data: CreateAgentConfigApiAgentConfigsPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateAgentConfigApiAgentConfigsPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createAgentConfigApiAgentConfigsPostMutationKey()

  const baseOptions = createAgentConfigApiAgentConfigsPostMutationOptions(config) as UseMutationOptions<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, {data: CreateAgentConfigApiAgentConfigsPostMutationRequest}, TContext>

  return useMutation<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, {data: CreateAgentConfigApiAgentConfigsPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateAgentConfigApiAgentConfigsPostMutationResponse, ResponseErrorConfig<CreateAgentConfigApiAgentConfigsPost422>, {data: CreateAgentConfigApiAgentConfigsPostMutationRequest}, TContext>
}