/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, GetAgentConfigApiAgentConfigsAgentIdGetPathParams, GetAgentConfigApiAgentConfigsAgentIdGet422 } from "../../types/GetAgentConfigApiAgentConfigsAgentIdGet";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAgentConfigApiAgentConfigsAgentIdGetQueryKey = (agent_id: GetAgentConfigApiAgentConfigsAgentIdGetPathParams["agent_id"]) => [{ url: '/api/agent-configs/:agent_id', params: {agent_id:agent_id} }] as const

export type GetAgentConfigApiAgentConfigsAgentIdGetQueryKey = ReturnType<typeof getAgentConfigApiAgentConfigsAgentIdGetQueryKey>

/**
 * @description Get a specific agent configuration from Retell AI.This endpoint returns only the essential agent details: agent_id, name, and prompt.Args:    agent_id: The ID of the agent to retrieveReturns:    AgentGetResponse with agent_id, name, and prompt
 * @summary Get Agent Config
 * {@link /api/agent-configs/:agent_id}
 */
export async function getAgentConfigApiAgentConfigsAgentIdGet(agent_id: GetAgentConfigApiAgentConfigsAgentIdGetPathParams["agent_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, ResponseErrorConfig<GetAgentConfigApiAgentConfigsAgentIdGet422>, unknown>({ method : "GET", url : `/api/agent-configs/${agent_id}`, ... requestConfig })  
  return res.data
}

export function getAgentConfigApiAgentConfigsAgentIdGetQueryOptions(agent_id: GetAgentConfigApiAgentConfigsAgentIdGetPathParams["agent_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAgentConfigApiAgentConfigsAgentIdGetQueryKey(agent_id)
  return queryOptions<GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, ResponseErrorConfig<GetAgentConfigApiAgentConfigsAgentIdGet422>, GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, typeof queryKey>({
   enabled: !!(agent_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAgentConfigApiAgentConfigsAgentIdGet(agent_id, config)
   },
  })
}

/**
 * @description Get a specific agent configuration from Retell AI.This endpoint returns only the essential agent details: agent_id, name, and prompt.Args:    agent_id: The ID of the agent to retrieveReturns:    AgentGetResponse with agent_id, name, and prompt
 * @summary Get Agent Config
 * {@link /api/agent-configs/:agent_id}
 */
export function useGetAgentConfigApiAgentConfigsAgentIdGet<TData = GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, TQueryData = GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, TQueryKey extends QueryKey = GetAgentConfigApiAgentConfigsAgentIdGetQueryKey>(agent_id: GetAgentConfigApiAgentConfigsAgentIdGetPathParams["agent_id"], options: 
{
  query?: Partial<QueryObserverOptions<GetAgentConfigApiAgentConfigsAgentIdGetQueryResponse, ResponseErrorConfig<GetAgentConfigApiAgentConfigsAgentIdGet422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAgentConfigApiAgentConfigsAgentIdGetQueryKey(agent_id)

  const query = useQuery({
   ...getAgentConfigApiAgentConfigsAgentIdGetQueryOptions(agent_id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetAgentConfigApiAgentConfigsAgentIdGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}