/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse } from "../../types/GetInitialPromptApiAgentConfigsInitialPromptGet";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getInitialPromptApiAgentConfigsInitialPromptGetQueryKey = () => [{ url: '/api/agent-configs/initial-prompt' }] as const

export type GetInitialPromptApiAgentConfigsInitialPromptGetQueryKey = ReturnType<typeof getInitialPromptApiAgentConfigsInitialPromptGetQueryKey>

/**
 * @description Get the initial prompt template for creating new agents.Returns the portion of the system prompt that comes after the styleguardrails, which can be used as a starting point for custom prompts.Returns:    dict with "prompt" key containing the initial template
 * @summary Get Initial Prompt
 * {@link /api/agent-configs/initial-prompt}
 */
export async function getInitialPromptApiAgentConfigsInitialPromptGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/agent-configs/initial-prompt`, ... requestConfig })  
  return res.data
}

export function getInitialPromptApiAgentConfigsInitialPromptGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getInitialPromptApiAgentConfigsInitialPromptGetQueryKey()
  return queryOptions<GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, ResponseErrorConfig<Error>, GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getInitialPromptApiAgentConfigsInitialPromptGet(config)
   },
  })
}

/**
 * @description Get the initial prompt template for creating new agents.Returns the portion of the system prompt that comes after the styleguardrails, which can be used as a starting point for custom prompts.Returns:    dict with "prompt" key containing the initial template
 * @summary Get Initial Prompt
 * {@link /api/agent-configs/initial-prompt}
 */
export function useGetInitialPromptApiAgentConfigsInitialPromptGet<TData = GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, TQueryData = GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, TQueryKey extends QueryKey = GetInitialPromptApiAgentConfigsInitialPromptGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetInitialPromptApiAgentConfigsInitialPromptGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getInitialPromptApiAgentConfigsInitialPromptGetQueryKey()

  const query = useQuery({
   ...getInitialPromptApiAgentConfigsInitialPromptGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}