/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ListAgentConfigsApiAgentConfigsGetQueryResponse, ListAgentConfigsApiAgentConfigsGetQueryParams, ListAgentConfigsApiAgentConfigsGet422 } from "../../types/ListAgentConfigsApiAgentConfigsGet";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listAgentConfigsApiAgentConfigsGetQueryKey = (params?: ListAgentConfigsApiAgentConfigsGetQueryParams) => [{ url: '/api/agent-configs' }, ...(params ? [params] : [])] as const

export type ListAgentConfigsApiAgentConfigsGetQueryKey = ReturnType<typeof listAgentConfigsApiAgentConfigsGetQueryKey>

/**
 * @description List all agent configurations from Retell AI.Args:    limit: Number of agents to return (1-1000, default 1000)    pagination_key: Agent ID to continue fetching from (for pagination)Returns:    List of AgentResponse objects from Retell SDK
 * @summary List Agent Configs
 * {@link /api/agent-configs}
 */
export async function listAgentConfigsApiAgentConfigsGet(params?: ListAgentConfigsApiAgentConfigsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListAgentConfigsApiAgentConfigsGetQueryResponse, ResponseErrorConfig<ListAgentConfigsApiAgentConfigsGet422>, unknown>({ method : "GET", url : `/api/agent-configs`, params, ... requestConfig })  
  return res.data
}

export function listAgentConfigsApiAgentConfigsGetQueryOptions(params?: ListAgentConfigsApiAgentConfigsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listAgentConfigsApiAgentConfigsGetQueryKey(params)
  return queryOptions<ListAgentConfigsApiAgentConfigsGetQueryResponse, ResponseErrorConfig<ListAgentConfigsApiAgentConfigsGet422>, ListAgentConfigsApiAgentConfigsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listAgentConfigsApiAgentConfigsGet(params, config)
   },
  })
}

/**
 * @description List all agent configurations from Retell AI.Args:    limit: Number of agents to return (1-1000, default 1000)    pagination_key: Agent ID to continue fetching from (for pagination)Returns:    List of AgentResponse objects from Retell SDK
 * @summary List Agent Configs
 * {@link /api/agent-configs}
 */
export function useListAgentConfigsApiAgentConfigsGet<TData = ListAgentConfigsApiAgentConfigsGetQueryResponse, TQueryData = ListAgentConfigsApiAgentConfigsGetQueryResponse, TQueryKey extends QueryKey = ListAgentConfigsApiAgentConfigsGetQueryKey>(params?: ListAgentConfigsApiAgentConfigsGetQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListAgentConfigsApiAgentConfigsGetQueryResponse, ResponseErrorConfig<ListAgentConfigsApiAgentConfigsGet422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listAgentConfigsApiAgentConfigsGetQueryKey(params)

  const query = useQuery({
   ...listAgentConfigsApiAgentConfigsGetQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<ListAgentConfigsApiAgentConfigsGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}