/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest, UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams, UpdateAgentConfigApiAgentConfigsAgentIdPatch422 } from "../../types/UpdateAgentConfigApiAgentConfigsAgentIdPatch";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateAgentConfigApiAgentConfigsAgentIdPatchMutationKey = () => [{ url: '/api/agent-configs/:agent_id' }] as const

export type UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationKey = ReturnType<typeof updateAgentConfigApiAgentConfigsAgentIdPatchMutationKey>

/**
 * @description Update an existing agent configuration in Retell AI.This is a light wrapper that allows updating:- The prompt (creates a new LLM and updates the agent's response_engine)- The agent nameAt least one field must be provided.Args:    agent_id: The ID of the agent to update    request: Agent update request with optional prompt and/or agent_nameReturns:    AgentResponse: The updated agent from Retell SDK
 * @summary Update Agent Config
 * {@link /api/agent-configs/:agent_id}
 */
export async function updateAgentConfigApiAgentConfigsAgentIdPatch(agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest, config: Partial<RequestConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest>({ method : "PATCH", url : `/api/agent-configs/${agent_id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function updateAgentConfigApiAgentConfigsAgentIdPatchMutationOptions(config: Partial<RequestConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateAgentConfigApiAgentConfigsAgentIdPatchMutationKey()
  return mutationOptions<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, {agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ agent_id, data }) => {
      return updateAgentConfigApiAgentConfigsAgentIdPatch(agent_id, data, config)
    },
  })
}

/**
 * @description Update an existing agent configuration in Retell AI.This is a light wrapper that allows updating:- The prompt (creates a new LLM and updates the agent's response_engine)- The agent nameAt least one field must be provided.Args:    agent_id: The ID of the agent to update    request: Agent update request with optional prompt and/or agent_nameReturns:    AgentResponse: The updated agent from Retell SDK
 * @summary Update Agent Config
 * {@link /api/agent-configs/:agent_id}
 */
export function useUpdateAgentConfigApiAgentConfigsAgentIdPatch<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, {agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateAgentConfigApiAgentConfigsAgentIdPatchMutationKey()

  const baseOptions = updateAgentConfigApiAgentConfigsAgentIdPatchMutationOptions(config) as UseMutationOptions<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, {agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest}, TContext>

  return useMutation<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, {agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationResponse, ResponseErrorConfig<UpdateAgentConfigApiAgentConfigsAgentIdPatch422>, {agent_id: UpdateAgentConfigApiAgentConfigsAgentIdPatchPathParams["agent_id"], data?: UpdateAgentConfigApiAgentConfigsAgentIdPatchMutationRequest}, TContext>
}