/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateWebCallApiCallswebcallPostMutationRequest, CreateWebCallApiCallswebcallPostMutationResponse, CreateWebCallApiCallswebcallPost422 } from "../../types/CreateWebCallApiCallswebcallPost";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createWebCallApiCallswebcallPostMutationKey = () => [{ url: '/api/callswebcall/' }] as const

export type CreateWebCallApiCallswebcallPostMutationKey = ReturnType<typeof createWebCallApiCallswebcallPostMutationKey>

/**
 * @description Create a web call via Retell AI.This endpoint creates a web call and returns an access token that can be usedby the frontend to join the call.Args:    request: Web call creation request with agent_id and optional metadataReturns:    Call object from Retell SDK containing access_token and call details
 * @summary Create Web Call
 * {@link /api/callswebcall/}
 */
export async function createWebCallApiCallswebcallPost(data: CreateWebCallApiCallswebcallPostMutationRequest, config: Partial<RequestConfig<CreateWebCallApiCallswebcallPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, CreateWebCallApiCallswebcallPostMutationRequest>({ method : "POST", url : `/api/callswebcall/`, data : requestData, ... requestConfig })  
  return res.data
}

export function createWebCallApiCallswebcallPostMutationOptions(config: Partial<RequestConfig<CreateWebCallApiCallswebcallPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createWebCallApiCallswebcallPostMutationKey()
  return mutationOptions<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, {data: CreateWebCallApiCallswebcallPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createWebCallApiCallswebcallPost(data, config)
    },
  })
}

/**
 * @description Create a web call via Retell AI.This endpoint creates a web call and returns an access token that can be usedby the frontend to join the call.Args:    request: Web call creation request with agent_id and optional metadataReturns:    Call object from Retell SDK containing access_token and call details
 * @summary Create Web Call
 * {@link /api/callswebcall/}
 */
export function useCreateWebCallApiCallswebcallPost<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, {data: CreateWebCallApiCallswebcallPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateWebCallApiCallswebcallPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createWebCallApiCallswebcallPostMutationKey()

  const baseOptions = createWebCallApiCallswebcallPostMutationOptions(config) as UseMutationOptions<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, {data: CreateWebCallApiCallswebcallPostMutationRequest}, TContext>

  return useMutation<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, {data: CreateWebCallApiCallswebcallPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateWebCallApiCallswebcallPostMutationResponse, ResponseErrorConfig<CreateWebCallApiCallswebcallPost422>, {data: CreateWebCallApiCallswebcallPostMutationRequest}, TContext>
}