/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetCallApiCallsCallIdGetQueryResponse, GetCallApiCallsCallIdGetPathParams, GetCallApiCallsCallIdGet422 } from "../../types/GetCallApiCallsCallIdGet";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCallApiCallsCallIdGetQueryKey = (call_id: GetCallApiCallsCallIdGetPathParams["call_id"]) => [{ url: '/api/calls/:call_id', params: {call_id:call_id} }] as const

export type GetCallApiCallsCallIdGetQueryKey = ReturnType<typeof getCallApiCallsCallIdGetQueryKey>

/**
 * @description Get a specific call.
 * @summary Get Call
 * {@link /api/calls/:call_id}
 */
export async function getCallApiCallsCallIdGet(call_id: GetCallApiCallsCallIdGetPathParams["call_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCallApiCallsCallIdGetQueryResponse, ResponseErrorConfig<GetCallApiCallsCallIdGet422>, unknown>({ method : "GET", url : `/api/calls/${call_id}`, ... requestConfig })  
  return res.data
}

export function getCallApiCallsCallIdGetQueryOptions(call_id: GetCallApiCallsCallIdGetPathParams["call_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCallApiCallsCallIdGetQueryKey(call_id)
  return queryOptions<GetCallApiCallsCallIdGetQueryResponse, ResponseErrorConfig<GetCallApiCallsCallIdGet422>, GetCallApiCallsCallIdGetQueryResponse, typeof queryKey>({
   enabled: !!(call_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCallApiCallsCallIdGet(call_id, config)
   },
  })
}

/**
 * @description Get a specific call.
 * @summary Get Call
 * {@link /api/calls/:call_id}
 */
export function useGetCallApiCallsCallIdGet<TData = GetCallApiCallsCallIdGetQueryResponse, TQueryData = GetCallApiCallsCallIdGetQueryResponse, TQueryKey extends QueryKey = GetCallApiCallsCallIdGetQueryKey>(call_id: GetCallApiCallsCallIdGetPathParams["call_id"], options: 
{
  query?: Partial<QueryObserverOptions<GetCallApiCallsCallIdGetQueryResponse, ResponseErrorConfig<GetCallApiCallsCallIdGet422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCallApiCallsCallIdGetQueryKey(call_id)

  const query = useQuery({
   ...getCallApiCallsCallIdGetQueryOptions(call_id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetCallApiCallsCallIdGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}