/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ListCallsApiCallsGetQueryResponse, ListCallsApiCallsGetQueryParams, ListCallsApiCallsGet422 } from "../../types/ListCallsApiCallsGet";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listCallsApiCallsGetQueryKey = (params?: ListCallsApiCallsGetQueryParams) => [{ url: '/api/calls' }, ...(params ? [params] : [])] as const

export type ListCallsApiCallsGetQueryKey = ReturnType<typeof listCallsApiCallsGetQueryKey>

/**
 * @description List all calls.
 * @summary List Calls
 * {@link /api/calls}
 */
export async function listCallsApiCallsGet(params?: ListCallsApiCallsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListCallsApiCallsGetQueryResponse, ResponseErrorConfig<ListCallsApiCallsGet422>, unknown>({ method : "GET", url : `/api/calls`, params, ... requestConfig })  
  return res.data
}

export function listCallsApiCallsGetQueryOptions(params?: ListCallsApiCallsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listCallsApiCallsGetQueryKey(params)
  return queryOptions<ListCallsApiCallsGetQueryResponse, ResponseErrorConfig<ListCallsApiCallsGet422>, ListCallsApiCallsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listCallsApiCallsGet(params, config)
   },
  })
}

/**
 * @description List all calls.
 * @summary List Calls
 * {@link /api/calls}
 */
export function useListCallsApiCallsGet<TData = ListCallsApiCallsGetQueryResponse, TQueryData = ListCallsApiCallsGetQueryResponse, TQueryKey extends QueryKey = ListCallsApiCallsGetQueryKey>(params?: ListCallsApiCallsGetQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListCallsApiCallsGetQueryResponse, ResponseErrorConfig<ListCallsApiCallsGet422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listCallsApiCallsGetQueryKey(params)

  const query = useQuery({
   ...listCallsApiCallsGetQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<ListCallsApiCallsGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}