/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TriggerCallApiCallsTriggerPostMutationRequest, TriggerCallApiCallsTriggerPostMutationResponse, TriggerCallApiCallsTriggerPost422 } from "../../types/TriggerCallApiCallsTriggerPost";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const triggerCallApiCallsTriggerPostMutationKey = () => [{ url: '/api/calls/trigger' }] as const

export type TriggerCallApiCallsTriggerPostMutationKey = ReturnType<typeof triggerCallApiCallsTriggerPostMutationKey>

/**
 * @description Trigger a new call via Retell AI.TODO: Implement actual Retell API integration
 * @summary Trigger Call
 * {@link /api/calls/trigger}
 */
export async function triggerCallApiCallsTriggerPost(data: TriggerCallApiCallsTriggerPostMutationRequest, config: Partial<RequestConfig<TriggerCallApiCallsTriggerPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, TriggerCallApiCallsTriggerPostMutationRequest>({ method : "POST", url : `/api/calls/trigger`, data : requestData, ... requestConfig })  
  return res.data
}

export function triggerCallApiCallsTriggerPostMutationOptions(config: Partial<RequestConfig<TriggerCallApiCallsTriggerPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = triggerCallApiCallsTriggerPostMutationKey()
  return mutationOptions<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, {data: TriggerCallApiCallsTriggerPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return triggerCallApiCallsTriggerPost(data, config)
    },
  })
}

/**
 * @description Trigger a new call via Retell AI.TODO: Implement actual Retell API integration
 * @summary Trigger Call
 * {@link /api/calls/trigger}
 */
export function useTriggerCallApiCallsTriggerPost<TContext>(options: 
{
  mutation?: UseMutationOptions<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, {data: TriggerCallApiCallsTriggerPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TriggerCallApiCallsTriggerPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? triggerCallApiCallsTriggerPostMutationKey()

  const baseOptions = triggerCallApiCallsTriggerPostMutationOptions(config) as UseMutationOptions<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, {data: TriggerCallApiCallsTriggerPostMutationRequest}, TContext>

  return useMutation<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, {data: TriggerCallApiCallsTriggerPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<TriggerCallApiCallsTriggerPostMutationResponse, ResponseErrorConfig<TriggerCallApiCallsTriggerPost422>, {data: TriggerCallApiCallsTriggerPostMutationRequest}, TContext>
}