/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateWebCallApiWebCallsPostMutationRequest, CreateWebCallApiWebCallsPostMutationResponse, CreateWebCallApiWebCallsPost422 } from "../../types/CreateWebCallApiWebCallsPost";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createWebCallApiWebCallsPostMutationKey = () => [{ url: '/api/web-calls' }] as const

export type CreateWebCallApiWebCallsPostMutationKey = ReturnType<typeof createWebCallApiWebCallsPostMutationKey>

/**
 * @description Create a web call via Retell AI.This endpoint creates a web call and returns an access token that can be usedby the frontend to join the call.Args:    request: Web call creation request with agent_id and optional metadataReturns:    Call object from Retell SDK containing access_token and call details
 * @summary Create Web Call
 * {@link /api/web-calls}
 */
export async function createWebCallApiWebCallsPost(data: CreateWebCallApiWebCallsPostMutationRequest, config: Partial<RequestConfig<CreateWebCallApiWebCallsPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, CreateWebCallApiWebCallsPostMutationRequest>({ method : "POST", url : `/api/web-calls`, data : requestData, ... requestConfig })  
  return res.data
}

export function createWebCallApiWebCallsPostMutationOptions(config: Partial<RequestConfig<CreateWebCallApiWebCallsPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createWebCallApiWebCallsPostMutationKey()
  return mutationOptions<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, {data: CreateWebCallApiWebCallsPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createWebCallApiWebCallsPost(data, config)
    },
  })
}

/**
 * @description Create a web call via Retell AI.This endpoint creates a web call and returns an access token that can be usedby the frontend to join the call.Args:    request: Web call creation request with agent_id and optional metadataReturns:    Call object from Retell SDK containing access_token and call details
 * @summary Create Web Call
 * {@link /api/web-calls}
 */
export function useCreateWebCallApiWebCallsPost<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, {data: CreateWebCallApiWebCallsPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateWebCallApiWebCallsPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createWebCallApiWebCallsPostMutationKey()

  const baseOptions = createWebCallApiWebCallsPostMutationOptions(config) as UseMutationOptions<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, {data: CreateWebCallApiWebCallsPostMutationRequest}, TContext>

  return useMutation<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, {data: CreateWebCallApiWebCallsPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateWebCallApiWebCallsPostMutationResponse, ResponseErrorConfig<CreateWebCallApiWebCallsPost422>, {data: CreateWebCallApiWebCallsPostMutationRequest}, TContext>
}