/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RetellWebhookApiWebhooksRetellPostMutationResponse } from "../../types/RetellWebhookApiWebhooksRetellPost";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const retellWebhookApiWebhooksRetellPostMutationKey = () => [{ url: '/api/webhooks/retell' }] as const

export type RetellWebhookApiWebhooksRetellPostMutationKey = ReturnType<typeof retellWebhookApiWebhooksRetellPostMutationKey>

/**
 * @description Receive webhooks from Retell AI.Events:- call_started: Call has begun- call_ended: Call has completed/failed- call_analyzed: Call analysis is complete (includes transcript)Note: Must respond within 10 seconds. Processing happens in background.
 * @summary Retell Webhook
 * {@link /api/webhooks/retell}
 */
export async function retellWebhookApiWebhooksRetellPost(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : `/api/webhooks/retell`, ... requestConfig })  
  return res.data
}

export function retellWebhookApiWebhooksRetellPostMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = retellWebhookApiWebhooksRetellPostMutationKey()
  return mutationOptions<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, void, typeof mutationKey>({
    mutationKey,
    mutationFn: async() => {
      return retellWebhookApiWebhooksRetellPost(config)
    },
  })
}

/**
 * @description Receive webhooks from Retell AI.Events:- call_started: Call has begun- call_ended: Call has completed/failed- call_analyzed: Call analysis is complete (includes transcript)Note: Must respond within 10 seconds. Processing happens in background.
 * @summary Retell Webhook
 * {@link /api/webhooks/retell}
 */
export function useRetellWebhookApiWebhooksRetellPost<TContext>(options: 
{
  mutation?: UseMutationOptions<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? retellWebhookApiWebhooksRetellPostMutationKey()

  const baseOptions = retellWebhookApiWebhooksRetellPostMutationOptions(config) as UseMutationOptions<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, void, TContext>

  return useMutation<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<RetellWebhookApiWebhooksRetellPostMutationResponse, ResponseErrorConfig<Error>, void, TContext>
}