/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Minimal request schema for creating a new agent via our API.
 */
export const agentCreateRequestSchema = z.object({
    "prompt": z.string().min(1).describe("The system prompt that defines the agent's behavior and personality"),
"agent_name": z.optional(z.union([z.string(), z.null()]).describe("Optional name for the agent (for internal reference)"))
    }).describe("Minimal request schema for creating a new agent via our API.")