/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { piiConfigSchema } from "./piiConfigSchema";
import { postCallAnalysisDataBooleanAnalysisDataSchema } from "./postCallAnalysisDataBooleanAnalysisDataSchema";
import { postCallAnalysisDataEnumAnalysisDataSchema } from "./postCallAnalysisDataEnumAnalysisDataSchema";
import { postCallAnalysisDataNumberAnalysisDataSchema } from "./postCallAnalysisDataNumberAnalysisDataSchema";
import { postCallAnalysisDataStringAnalysisDataSchema } from "./postCallAnalysisDataStringAnalysisDataSchema";
import { pronunciationDictionarySchema } from "./pronunciationDictionarySchema";
import { responseEngineResponseEngineConversationFlowSchema } from "./responseEngineResponseEngineConversationFlowSchema";
import { responseEngineResponseEngineCustomLmSchema } from "./responseEngineResponseEngineCustomLmSchema";
import { responseEngineResponseEngineRetellLmSchema } from "./responseEngineResponseEngineRetellLmSchema";
import { userDtmfOptionsSchema } from "./userDtmfOptionsSchema";
import { voicemailOptionSchema } from "./voicemailOptionSchema";
import { z } from "zod/v4";

export const agentResponseSchema = z.object({
    "agent_id": z.string(),
"last_modification_timestamp": z.int(),
get "response_engine"(){
                return z.union([responseEngineResponseEngineRetellLmSchema, responseEngineResponseEngineCustomLmSchema, responseEngineResponseEngineConversationFlowSchema])
              },
"version": z.int(),
"voice_id": z.string(),
"agent_name": z.optional(z.union([z.string(), z.null()])),
"allow_user_dtmf": z.optional(z.union([z.boolean(), z.null()])),
"ambient_sound": z.optional(z.union([z.enum(["coffee-shop", "convention-hall", "summer-outdoor", "mountain-outdoor", "static-noise", "call-center"]), z.null()])),
"ambient_sound_volume": z.optional(z.union([z.number(), z.null()])),
"analysis_successful_prompt": z.optional(z.union([z.string(), z.null()])),
"analysis_summary_prompt": z.optional(z.union([z.string(), z.null()])),
"backchannel_frequency": z.optional(z.union([z.number(), z.null()])),
"backchannel_words": z.optional(z.union([z.array(z.string()), z.null()])),
"begin_message_delay_ms": z.optional(z.union([z.int(), z.null()])),
"boosted_keywords": z.optional(z.union([z.array(z.string()), z.null()])),
"data_storage_setting": z.optional(z.union([z.enum(["everything", "everything_except_pii", "basic_attributes_only"]), z.null()])),
"denoising_mode": z.optional(z.union([z.enum(["noise-cancellation", "noise-and-background-speech-cancellation"]), z.null()])),
"enable_backchannel": z.optional(z.union([z.boolean(), z.null()])),
"enable_voicemail_detection": z.optional(z.union([z.boolean(), z.null()])),
"end_call_after_silence_ms": z.optional(z.union([z.int(), z.null()])),
"fallback_voice_ids": z.optional(z.union([z.array(z.string()), z.null()])),
"interruption_sensitivity": z.optional(z.union([z.number(), z.null()])),
"is_published": z.optional(z.union([z.boolean(), z.null()])),
"language": z.optional(z.union([z.enum(["en-US", "en-IN", "en-GB", "en-AU", "en-NZ", "de-DE", "es-ES", "es-419", "hi-IN", "fr-FR", "fr-CA", "ja-JP", "pt-PT", "pt-BR", "zh-CN", "ru-RU", "it-IT", "ko-KR", "nl-NL", "nl-BE", "pl-PL", "tr-TR", "vi-VN", "ro-RO", "bg-BG", "ca-ES", "th-TH", "da-DK", "fi-FI", "el-GR", "hu-HU", "id-ID", "no-NO", "sk-SK", "sv-SE", "ms-MY", "af-ZA", "ar-SA", "az-AZ", "bs-BA", "cy-GB", "fa-IR", "fil-PH", "gl-ES", "he-IL", "hr-HR", "hy-AM", "is-IS", "kk-KZ", "kn-IN", "mk-MK", "mr-IN", "ne-NP", "sl-SI", "sr-RS", "sw-KE", "ta-IN", "ur-IN", "yue-CN", "uk-UA", "multi"]), z.null()])),
"max_call_duration_ms": z.optional(z.union([z.int(), z.null()])),
"normalize_for_speech": z.optional(z.union([z.boolean(), z.null()])),
"opt_in_signed_url": z.optional(z.union([z.boolean(), z.null()])),
get "pii_config"(){
                return z.union([piiConfigSchema, z.null()]).optional()
              },
get "post_call_analysis_data"(){
                return z.union([z.array(z.union([postCallAnalysisDataStringAnalysisDataSchema, postCallAnalysisDataEnumAnalysisDataSchema, postCallAnalysisDataBooleanAnalysisDataSchema, postCallAnalysisDataNumberAnalysisDataSchema])), z.null()]).optional()
              },
"post_call_analysis_model": z.optional(z.union([z.enum(["gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-5", "gpt-5.1", "gpt-5.2", "gpt-5-mini", "gpt-5-nano", "claude-4.5-sonnet", "claude-4.5-haiku", "gemini-2.5-flash", "gemini-2.5-flash-lite"]), z.null()])),
get "pronunciation_dictionary"(){
                return z.union([z.array(pronunciationDictionarySchema), z.null()]).optional()
              },
"reminder_max_count": z.optional(z.union([z.int(), z.null()])),
"reminder_trigger_ms": z.optional(z.union([z.number(), z.null()])),
"responsiveness": z.optional(z.union([z.number(), z.null()])),
"ring_duration_ms": z.optional(z.union([z.int(), z.null()])),
"signed_url_expiration_ms": z.optional(z.union([z.int(), z.null()])),
"stt_mode": z.optional(z.union([z.enum(["fast", "accurate"]), z.null()])),
get "user_dtmf_options"(){
                return z.union([userDtmfOptionsSchema, z.null()]).optional()
              },
"version_description": z.optional(z.union([z.string(), z.null()])),
"vocab_specialization": z.optional(z.union([z.enum(["general", "medical"]), z.null()])),
"voice_model": z.optional(z.union([z.enum(["eleven_turbo_v2", "eleven_flash_v2", "eleven_turbo_v2_5", "eleven_flash_v2_5", "eleven_multilingual_v2", "sonic-2", "sonic-3", "sonic-turbo", "tts-1", "gpt-4o-mini-tts", "speech-02-turbo"]), z.null()])),
"voice_speed": z.optional(z.union([z.number(), z.null()])),
"voice_temperature": z.optional(z.union([z.number(), z.null()])),
"voicemail_detection_timeout_ms": z.optional(z.union([z.int(), z.null()])),
"voicemail_message": z.optional(z.union([z.string(), z.null()])),
get "voicemail_option"(){
                return z.union([voicemailOptionSchema, z.null()]).optional()
              },
"volume": z.optional(z.union([z.number(), z.null()])),
"webhook_timeout_ms": z.optional(z.union([z.int(), z.null()])),
"webhook_url": z.optional(z.union([z.string(), z.null()]))
    }).catchall(z.any())