/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Response schema for retrieving a single agent.
 */
export const agentGetResponseSchema = z.object({
    "agent_id": z.string().describe("Unique identifier for the agent"),
"name": z.optional(z.union([z.string(), z.null()]).describe("Name of the agent (for internal reference)")),
"prompt": z.optional(z.union([z.string(), z.null()]).describe("The system prompt defining agent behavior"))
    }).describe("Response schema for retrieving a single agent.")