/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Minimal request schema for updating an existing agent via our API.
 */
export const agentUpdateRequestSchema = z.object({
    "prompt": z.optional(z.union([z.string(), z.null()]).describe("Updated system prompt (creates a new LLM and updates the agent)")),
"agent_name": z.optional(z.union([z.string(), z.null()]).describe("Updated name for the agent (for internal reference)"))
    }).describe("Minimal request schema for updating an existing agent via our API.")