/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Schema for triggering a call.
 */
export const callCreateSchema = z.object({
    "retell_agent_id": z.string(),
"driver_name": z.string(),
"phone_number": z.string(),
"load_number": z.string()
    }).describe("Schema for triggering a call.")