/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { agentCreateRequestSchema } from "./agentCreateRequestSchema";
import { agentResponseSchema } from "./agentResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const createAgentConfigApiAgentConfigsPost201Schema = z.lazy(() => agentResponseSchema)

/**
 * @description Validation Error
 */
export const createAgentConfigApiAgentConfigsPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createAgentConfigApiAgentConfigsPostMutationRequestSchema = z.lazy(() => agentCreateRequestSchema).describe("Minimal request schema for creating a new agent via our API.")

export const createAgentConfigApiAgentConfigsPostMutationResponseSchema = z.lazy(() => createAgentConfigApiAgentConfigsPost201Schema)