/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { webCallCreateRequestSchema } from "./webCallCreateRequestSchema";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const createWebCallApiWebCallsPost201Schema = z.any()

/**
 * @description Validation Error
 */
export const createWebCallApiWebCallsPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createWebCallApiWebCallsPostMutationRequestSchema = z.lazy(() => webCallCreateRequestSchema).describe("Schema for creating a web call.")

export const createWebCallApiWebCallsPostMutationResponseSchema = z.lazy(() => createWebCallApiWebCallsPost201Schema)