/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { callCreateSchema } from "./callCreateSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const createWebCallApiCallswebcallPost201Schema = z.any()

/**
 * @description Validation Error
 */
export const createWebCallApiCallswebcallPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createWebCallApiCallswebcallPostMutationRequestSchema = z.lazy(() => callCreateSchema).describe("Schema for triggering a call.")

export const createWebCallApiCallswebcallPostMutationResponseSchema = z.lazy(() => createWebCallApiCallswebcallPost201Schema)