/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { agentGetResponseSchema } from "./agentGetResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

export const getAgentConfigApiAgentConfigsAgentIdGetPathParamsSchema = z.object({
    "agent_id": z.string()
    })

/**
 * @description Successful Response
 */
export const getAgentConfigApiAgentConfigsAgentIdGet200Schema = z.lazy(() => agentGetResponseSchema).describe("Response schema for retrieving a single agent.")

/**
 * @description Validation Error
 */
export const getAgentConfigApiAgentConfigsAgentIdGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getAgentConfigApiAgentConfigsAgentIdGetQueryResponseSchema = z.lazy(() => getAgentConfigApiAgentConfigsAgentIdGet200Schema)