/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { callResponseSchema } from "./callResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

export const getCallApiCallsCallIdGetPathParamsSchema = z.object({
    "call_id": z.coerce.number().int()
    })

/**
 * @description Successful Response
 */
export const getCallApiCallsCallIdGet200Schema = z.lazy(() => callResponseSchema).describe("Schema for call response.")

/**
 * @description Validation Error
 */
export const getCallApiCallsCallIdGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getCallApiCallsCallIdGetQueryResponseSchema = z.lazy(() => getCallApiCallsCallIdGet200Schema)