/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { callResponseSchema } from "./callResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

export const listCallsApiCallsGetQueryParamsSchema = z.object({
    "skip": z.coerce.number().int().default(0),
"limit": z.coerce.number().int().default(100)
    })

/**
 * @description Successful Response
 */
export const listCallsApiCallsGet200Schema = z.array(z.lazy(() => callResponseSchema).describe("Schema for call response."))

/**
 * @description Validation Error
 */
export const listCallsApiCallsGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listCallsApiCallsGetQueryResponseSchema = z.lazy(() => listCallsApiCallsGet200Schema)