/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { agentResponseSchema } from "./agentResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

export const listAgentConfigsApiAgentConfigsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(1000).default(1000),
"pagination_key": z.optional(z.union([z.string(), z.null()]))
    })

/**
 * @description Successful Response
 */
export const listAgentConfigsApiAgentConfigsGet200Schema = z.array(z.lazy(() => agentResponseSchema))

/**
 * @description Validation Error
 */
export const listAgentConfigsApiAgentConfigsGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listAgentConfigsApiAgentConfigsGetQueryResponseSchema = z.lazy(() => listAgentConfigsApiAgentConfigsGet200Schema)