/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Configuration for PII scrubbing from transcripts and recordings.
 */
export const piiConfigSchema = z.object({
    "categories": z.array(z.enum(["person_name", "address", "email", "phone_number", "ssn", "passport", "driver_license", "credit_card", "bank_account", "password", "pin", "medical_id", "date_of_birth", "customer_account_number"])),
"mode": z.literal("post_call")
    }).catchall(z.any()).describe("Configuration for PII scrubbing from transcripts and recordings.")