/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postCallAnalysisDataStringAnalysisDataSchema = z.object({
    "description": z.string(),
"name": z.string(),
"type": z.literal("string"),
"examples": z.optional(z.union([z.array(z.string()), z.null()]))
    }).catchall(z.any())