/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postCallAnalysisDataNumberAnalysisDataSchema = z.object({
    "description": z.string(),
"name": z.string(),
"type": z.literal("number")
    }).catchall(z.any())