/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postCallAnalysisDataEnumAnalysisDataSchema = z.object({
    "choices": z.array(z.string()),
"description": z.string(),
"name": z.string(),
"type": z.literal("enum")
    }).catchall(z.any())