/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postCallAnalysisDataBooleanAnalysisDataSchema = z.object({
    "description": z.string(),
"name": z.string(),
"type": z.literal("boolean")
    }).catchall(z.any())