/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const pronunciationDictionarySchema = z.object({
    "alphabet": z.enum(["ipa", "cmu"]),
"phoneme": z.string(),
"word": z.string()
    }).catchall(z.any())