/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const responseEngineResponseEngineRetellLmSchema = z.object({
    "llm_id": z.string(),
"type": z.literal("retell-llm"),
"version": z.optional(z.union([z.number(), z.null()]))
    }).catchall(z.any())