/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const responseEngineResponseEngineConversationFlowSchema = z.object({
    "conversation_flow_id": z.string(),
"type": z.literal("conversation-flow"),
"version": z.optional(z.union([z.number(), z.null()]))
    }).catchall(z.any())