/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const responseEngineResponseEngineCustomLmSchema = z.object({
    "llm_websocket_url": z.string(),
"type": z.literal("custom-llm")
    }).catchall(z.any())