/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const retellWebhookApiWebhooksRetellPost204Schema = z.any()

export const retellWebhookApiWebhooksRetellPostMutationResponseSchema = z.lazy(() => retellWebhookApiWebhooksRetellPost204Schema)