/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const rootGet200Schema = z.any()

export const rootGetQueryResponseSchema = z.lazy(() => rootGet200Schema)