/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { callCreateSchema } from "./callCreateSchema";
import { callResponseSchema } from "./callResponseSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const triggerCallApiCallsTriggerPost201Schema = z.lazy(() => callResponseSchema).describe("Schema for call response.")

/**
 * @description Validation Error
 */
export const triggerCallApiCallsTriggerPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const triggerCallApiCallsTriggerPostMutationRequestSchema = z.lazy(() => callCreateSchema).describe("Schema for triggering a call.")

export const triggerCallApiCallsTriggerPostMutationResponseSchema = z.lazy(() => triggerCallApiCallsTriggerPost201Schema)