/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { agentResponseSchema } from "./agentResponseSchema";
import { agentUpdateRequestSchema } from "./agentUpdateRequestSchema";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { z } from "zod/v4";

export const updateAgentConfigApiAgentConfigsAgentIdPatchPathParamsSchema = z.object({
    "agent_id": z.string()
    })

/**
 * @description Successful Response
 */
export const updateAgentConfigApiAgentConfigsAgentIdPatch200Schema = z.lazy(() => agentResponseSchema)

/**
 * @description Validation Error
 */
export const updateAgentConfigApiAgentConfigsAgentIdPatch422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const updateAgentConfigApiAgentConfigsAgentIdPatchMutationRequestSchema = z.lazy(() => agentUpdateRequestSchema).describe("Minimal request schema for updating an existing agent via our API.")

export const updateAgentConfigApiAgentConfigsAgentIdPatchMutationResponseSchema = z.lazy(() => updateAgentConfigApiAgentConfigsAgentIdPatch200Schema)