/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const userDtmfOptionsSchema = z.object({
    "digit_limit": z.optional(z.union([z.number(), z.null()])),
"termination_key": z.optional(z.union([z.string(), z.null()])),
"timeout_ms": z.optional(z.union([z.int(), z.null()]))
    }).catchall(z.any())