/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const voicemailOptionActionVoicemailActionStaticTextSchema = z.object({
    "text": z.string(),
"type": z.literal("static_text")
    }).catchall(z.any())