/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const voicemailOptionActionVoicemailActionHangupSchema = z.object({
    "type": z.literal("hangup")
    }).catchall(z.any())