/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { voicemailOptionActionVoicemailActionBridgeTransferSchema } from "./voicemailOptionActionVoicemailActionBridgeTransferSchema";
import { voicemailOptionActionVoicemailActionHangupSchema } from "./voicemailOptionActionVoicemailActionHangupSchema";
import { voicemailOptionActionVoicemailActionPromptSchema } from "./voicemailOptionActionVoicemailActionPromptSchema";
import { voicemailOptionActionVoicemailActionStaticTextSchema } from "./voicemailOptionActionVoicemailActionStaticTextSchema";
import { z } from "zod/v4";

/**
 * @description If this option is set, the call will try to detect voicemail in the first 3 minutes of the call. Actions defined (hangup, or leave a message) will be applied when the voicemail is detected. Set this to null to disable voicemail detection.
 */
export const voicemailOptionSchema = z.object({
    get "action"(){
                return z.union([voicemailOptionActionVoicemailActionPromptSchema, voicemailOptionActionVoicemailActionStaticTextSchema, voicemailOptionActionVoicemailActionHangupSchema, voicemailOptionActionVoicemailActionBridgeTransferSchema])
              }
    }).catchall(z.any()).describe("If this option is set, the call will try to detect voicemail in the first 3 minutes of the call. Actions defined (hangup, or leave a message) will be applied when the voicemail is detected. Set this to null to disable voicemail detection.")