/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const voicemailOptionActionVoicemailActionBridgeTransferSchema = z.object({
    "type": z.literal("bridge_transfer")
    }).catchall(z.any())