/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Schema for creating a web call.
 */
export const webCallCreateRequestSchema = z.object({
    "agent_id": z.string().describe("Unique ID of agent used for the call"),
"metadata": z.optional(z.union([z.object({
    
    }).catchall(z.any()), z.null()]).describe("Arbitrary key-value storage for internal use (e.g., customer IDs)")),
"retell_llm_dynamic_variables": z.optional(z.union([z.object({
    
    }).catchall(z.string()), z.null()]).describe("Dynamic string variables to inject into prompt and tool descriptions"))
    }).describe("Schema for creating a web call.")